name: Heroku Awake

on:
  schedule:
    - cron: "*/35 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://bairro-alto.herokuapp.com/web-content/get-web-content"
