name: Heroku Awake

on:
  schedule:
    - cron: "*/35 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://fast-savannah-95653.herokuapp.com/"
